import pandas as pd


# sample code for test
def get_data(recommendations):
    sample_data = [
        {
            "perfume_name": "Gentleman Givenchy Réserve Privée",
            "year": 2022,
            "brand": "Givenchy",
            "image_url": "https://pimages.parfumo.de/480/158077_img-4050-givenchy-gentleman-givenchy-eau-de-parfum-reserve-privee_480.jpg",
            "notes_top": ["Italian bergamot"],
            "notes_heart": ["Chestnut", "Benzoin Siam"],
            "notes_base": ["Virginia cedar", "Haitian vetiver", "Indonesian patchouli"],
            "rating": 8.1,
            "link": "https://www.parfumo.net/Perfumes/Givenchy/gentleman-givenchy-reserve-privee",
        },
        {
            "perfume_name": "City of Stars",
            "year": 2022,
            "brand": "Louis Vuitton",
            "image_url": "https://pimages.parfumo.de/480/167670_img-2443-louis-vuitton-city-of-stars_480.jpg",
            "notes_top": [],
            "notes_heart": [],
            "notes_base": [
                "Blood orange",
                "Lemon",
                "Red mandarin orange",
                "Bergamot",
                "Lime",
                "Tiaré",
                "Sandalwood",
                "Musk",
            ],
            "rating": 7.2,
            "link": "https://www.parfumo.net/Perfumes/Louis_Vuitton/city-of-stars",
        },
        {
            "perfume_name": "Acqua di Giò pour Homme Eau de Parfum",
            "year": 2022,
            "brand": "Giorgio Armani",
            "image_url": "https://pimages.parfumo.de/480/160300_img-8398-giorgio-armani-acqua-di-gio-pour-homme-eau-de-parfum_480.jpg",
            "notes_top": ["Italian green mandarin orange", "Marine notes"],
            "notes_heart": [
                "Provençal clary sage",
                "Provençal lavender",
                "Madagascan geranium",
            ],
            "notes_base": ["Guatemala patchouly", "Haitian vetiver"],
            "rating": 7.2,
            "link": "https://www.parfumo.net/Perfumes/Giorgio_Armani/acqua-di-gio-pour-homme-eau-de-parfum",
        },
        {
            "perfume_name": "Apex",
            "year": 2022,
            "brand": "Roja Parfums",
            "image_url": "https://pimages.parfumo.de/480/165208_img-6247-roja-parfums-apex_480.jpg",
            "notes_top": ["Lemon", "Bergamot", "Mandarin orange", "Orange"],
            "notes_heart": ["Jasmine", "Cistus", "Pineapple"],
            "notes_base": [
                "Galbanum",
                "Elemi resin",
                "Patchouli",
                "Oakmoss",
                "Rum",
                "Tobacco",
                "Cypress",
                "Fir balsam",
                "Juniper berry",
                "Cashmere wood",
                "Sandalwood",
                "Benzoin",
                "Amber",
                "Frankincense",
                "Labdanum",
                "Leather",
                "Ambergris",
                "Musk",
            ],
            "rating": 7.0,
            "link": "https://www.parfumo.net/Perfumes/Roja_Parfums/apex",
        },
        {
            "perfume_name": "Terre d'Hermès Eau Givrée",
            "year": 2022,
            "brand": "Hermès",
            "image_url": "https://pimages.parfumo.de/480/164275_img-5053-hermes-terre-d-hermes-eau-givree_480.jpg",
            "notes_top": [],
            "notes_heart": [],
            "notes_base": ["Citron", "Juniper berry", "Nepalese Sichuan pepper"],
            "rating": 7.5,
            "link": "https://www.parfumo.net/Perfumes/Hermes/terre-d-hermes-eau-givree",
        },
    ]

    return sample_data
